use_frameworks!

platform :ios, '8.0'

target 'DWAdapter_Example' do
  pod 'DWAdapter', :path => '../'

  target 'DWAdapter_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
