use_frameworks!

platform :ios, '8.0'

target 'DWBaseAdapter_Example' do
  pod 'DWBaseAdapter', :path => '../'

  target 'DWBaseAdapter_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
